// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: articles/v1/article.proto

package article

import (
	v1 "github.com/chiquitav2/journalful/pkg/profile/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Doi             string                 `protobuf:"bytes,2,opt,name=doi,proto3" json:"doi,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Authors         []*v1.Author           `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"` // List of authors
	Abstract        *string                `protobuf:"bytes,5,opt,name=abstract,proto3,oneof" json:"abstract,omitempty"`
	PublicationYear *int32                 `protobuf:"varint,6,opt,name=publication_year,json=publicationYear,proto3,oneof" json:"publication_year,omitempty"`
	JournalName     *string                `protobuf:"bytes,7,opt,name=journal_name,json=journalName,proto3,oneof" json:"journal_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_articles_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetAuthors() []*v1.Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Article) GetAbstract() string {
	if x != nil && x.Abstract != nil {
		return *x.Abstract
	}
	return ""
}

func (x *Article) GetPublicationYear() int32 {
	if x != nil && x.PublicationYear != nil {
		return *x.PublicationYear
	}
	return 0
}

func (x *Article) GetJournalName() string {
	if x != nil && x.JournalName != nil {
		return *x.JournalName
	}
	return ""
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type GetArticleByDOIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doi           string                 `protobuf:"bytes,1,opt,name=doi,proto3" json:"doi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByDOIRequest) Reset() {
	*x = GetArticleByDOIRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByDOIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByDOIRequest) ProtoMessage() {}

func (x *GetArticleByDOIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByDOIRequest.ProtoReflect.Descriptor instead.
func (*GetArticleByDOIRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleByDOIRequest) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

type GetArticleByDOIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleByDOIResponse) Reset() {
	*x = GetArticleByDOIResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleByDOIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleByDOIResponse) ProtoMessage() {}

func (x *GetArticleByDOIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleByDOIResponse.ProtoReflect.Descriptor instead.
func (*GetArticleByDOIResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleByDOIResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`                         // Page number for pagination
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"` // Number of articles per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListArticlesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type CreateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Doi             string                 `protobuf:"bytes,1,opt,name=doi,proto3" json:"doi,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Authors         []*v1.Author           `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"` // List of authors
	Abstract        *string                `protobuf:"bytes,5,opt,name=abstract,proto3,oneof" json:"abstract,omitempty"`
	PublicationYear *int32                 `protobuf:"varint,6,opt,name=publication_year,json=publicationYear,proto3,oneof" json:"publication_year,omitempty"`
	JournalName     *string                `protobuf:"bytes,7,opt,name=journal_name,json=journalName,proto3,oneof" json:"journal_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *CreateArticleRequest) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetAuthors() []*v1.Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *CreateArticleRequest) GetAbstract() string {
	if x != nil && x.Abstract != nil {
		return *x.Abstract
	}
	return ""
}

func (x *CreateArticleRequest) GetPublicationYear() int32 {
	if x != nil && x.PublicationYear != nil {
		return *x.PublicationYear
	}
	return 0
}

func (x *CreateArticleRequest) GetJournalName() string {
	if x != nil && x.JournalName != nil {
		return *x.JournalName
	}
	return ""
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the newly created article
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *CreateArticleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Doi             string                 `protobuf:"bytes,2,opt,name=doi,proto3" json:"doi,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Abstract        *string                `protobuf:"bytes,4,opt,name=abstract,proto3,oneof" json:"abstract,omitempty"`
	PublicationYear *int32                 `protobuf:"varint,5,opt,name=publication_year,json=publicationYear,proto3,oneof" json:"publication_year,omitempty"`
	JournalName     *string                `protobuf:"bytes,6,opt,name=journal_name,json=journalName,proto3,oneof" json:"journal_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetAbstract() string {
	if x != nil && x.Abstract != nil {
		return *x.Abstract
	}
	return ""
}

func (x *UpdateArticleRequest) GetPublicationYear() int32 {
	if x != nil && x.PublicationYear != nil {
		return *x.PublicationYear
	}
	return 0
}

func (x *UpdateArticleRequest) GetJournalName() string {
	if x != nil && x.JournalName != nil {
		return *x.JournalName
	}
	return ""
}

type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{10}
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_articles_v1_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_articles_v1_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articles_v1_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_articles_v1_article_proto_rawDescGZIP(), []int{12}
}

var File_articles_v1_article_proto protoreflect.FileDescriptor

const file_articles_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x19articles/v1/article.proto\x12\x0fapi.articles.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17profile/v1/author.proto\"\x95\x03\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03doi\x18\x02 \x01(\tR\x03doi\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x120\n" +
	"\aauthors\x18\x04 \x03(\v2\x16.api.profile.v1.AuthorR\aauthors\x12\x1f\n" +
	"\babstract\x18\x05 \x01(\tH\x00R\babstract\x88\x01\x01\x12.\n" +
	"\x10publication_year\x18\x06 \x01(\x05H\x01R\x0fpublicationYear\x88\x01\x01\x12&\n" +
	"\fjournal_name\x18\a \x01(\tH\x02R\vjournalName\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_abstractB\x13\n" +
	"\x11_publication_yearB\x0f\n" +
	"\r_journal_name\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x12GetArticleResponse\x122\n" +
	"\aarticle\x18\x01 \x01(\v2\x18.api.articles.v1.ArticleR\aarticle\"*\n" +
	"\x16GetArticleByDOIRequest\x12\x10\n" +
	"\x03doi\x18\x01 \x01(\tR\x03doi\"M\n" +
	"\x17GetArticleByDOIResponse\x122\n" +
	"\aarticle\x18\x01 \x01(\v2\x18.api.articles.v1.ArticleR\aarticle\"g\n" +
	"\x13ListArticlesRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"L\n" +
	"\x14ListArticlesResponse\x124\n" +
	"\barticles\x18\x01 \x03(\v2\x18.api.articles.v1.ArticleR\barticles\"\x9c\x02\n" +
	"\x14CreateArticleRequest\x12\x10\n" +
	"\x03doi\x18\x01 \x01(\tR\x03doi\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x120\n" +
	"\aauthors\x18\x04 \x03(\v2\x16.api.profile.v1.AuthorR\aauthors\x12\x1f\n" +
	"\babstract\x18\x05 \x01(\tH\x00R\babstract\x88\x01\x01\x12.\n" +
	"\x10publication_year\x18\x06 \x01(\x05H\x01R\x0fpublicationYear\x88\x01\x01\x12&\n" +
	"\fjournal_name\x18\a \x01(\tH\x02R\vjournalName\x88\x01\x01B\v\n" +
	"\t_abstractB\x13\n" +
	"\x11_publication_yearB\x0f\n" +
	"\r_journal_name\"'\n" +
	"\x15CreateArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xfa\x01\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03doi\x18\x02 \x01(\tR\x03doi\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\babstract\x18\x04 \x01(\tH\x00R\babstract\x88\x01\x01\x12.\n" +
	"\x10publication_year\x18\x05 \x01(\x05H\x01R\x0fpublicationYear\x88\x01\x01\x12&\n" +
	"\fjournal_name\x18\x06 \x01(\tH\x02R\vjournalName\x88\x01\x01B\v\n" +
	"\t_abstractB\x13\n" +
	"\x11_publication_yearB\x0f\n" +
	"\r_journal_name\"\x17\n" +
	"\x15UpdateArticleResponse\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteArticleResponse2\xcb\x04\n" +
	"\x0fArticlesService\x12U\n" +
	"\n" +
	"GetArticle\x12\".api.articles.v1.GetArticleRequest\x1a#.api.articles.v1.GetArticleResponse\x12d\n" +
	"\x0fGetArticleByDOI\x12'.api.articles.v1.GetArticleByDOIRequest\x1a(.api.articles.v1.GetArticleByDOIResponse\x12[\n" +
	"\fListArticles\x12$.api.articles.v1.ListArticlesRequest\x1a%.api.articles.v1.ListArticlesResponse\x12^\n" +
	"\rCreateArticle\x12%.api.articles.v1.CreateArticleRequest\x1a&.api.articles.v1.CreateArticleResponse\x12^\n" +
	"\rUpdateArticle\x12%.api.articles.v1.UpdateArticleRequest\x1a&.api.articles.v1.UpdateArticleResponse\x12^\n" +
	"\rDeleteArticle\x12%.api.articles.v1.DeleteArticleRequest\x1a&.api.articles.v1.DeleteArticleResponseB:Z8github.com/chiquitav2/journalful/pkg/articles/v1;articleb\x06proto3"

var (
	file_articles_v1_article_proto_rawDescOnce sync.Once
	file_articles_v1_article_proto_rawDescData []byte
)

func file_articles_v1_article_proto_rawDescGZIP() []byte {
	file_articles_v1_article_proto_rawDescOnce.Do(func() {
		file_articles_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articles_v1_article_proto_rawDesc), len(file_articles_v1_article_proto_rawDesc)))
	})
	return file_articles_v1_article_proto_rawDescData
}

var file_articles_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_articles_v1_article_proto_goTypes = []any{
	(*Article)(nil),                 // 0: api.articles.v1.Article
	(*GetArticleRequest)(nil),       // 1: api.articles.v1.GetArticleRequest
	(*GetArticleResponse)(nil),      // 2: api.articles.v1.GetArticleResponse
	(*GetArticleByDOIRequest)(nil),  // 3: api.articles.v1.GetArticleByDOIRequest
	(*GetArticleByDOIResponse)(nil), // 4: api.articles.v1.GetArticleByDOIResponse
	(*ListArticlesRequest)(nil),     // 5: api.articles.v1.ListArticlesRequest
	(*ListArticlesResponse)(nil),    // 6: api.articles.v1.ListArticlesResponse
	(*CreateArticleRequest)(nil),    // 7: api.articles.v1.CreateArticleRequest
	(*CreateArticleResponse)(nil),   // 8: api.articles.v1.CreateArticleResponse
	(*UpdateArticleRequest)(nil),    // 9: api.articles.v1.UpdateArticleRequest
	(*UpdateArticleResponse)(nil),   // 10: api.articles.v1.UpdateArticleResponse
	(*DeleteArticleRequest)(nil),    // 11: api.articles.v1.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),   // 12: api.articles.v1.DeleteArticleResponse
	(*v1.Author)(nil),               // 13: api.profile.v1.Author
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_articles_v1_article_proto_depIdxs = []int32{
	13, // 0: api.articles.v1.Article.authors:type_name -> api.profile.v1.Author
	14, // 1: api.articles.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: api.articles.v1.Article.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: api.articles.v1.GetArticleResponse.article:type_name -> api.articles.v1.Article
	0,  // 4: api.articles.v1.GetArticleByDOIResponse.article:type_name -> api.articles.v1.Article
	0,  // 5: api.articles.v1.ListArticlesResponse.articles:type_name -> api.articles.v1.Article
	13, // 6: api.articles.v1.CreateArticleRequest.authors:type_name -> api.profile.v1.Author
	1,  // 7: api.articles.v1.ArticlesService.GetArticle:input_type -> api.articles.v1.GetArticleRequest
	3,  // 8: api.articles.v1.ArticlesService.GetArticleByDOI:input_type -> api.articles.v1.GetArticleByDOIRequest
	5,  // 9: api.articles.v1.ArticlesService.ListArticles:input_type -> api.articles.v1.ListArticlesRequest
	7,  // 10: api.articles.v1.ArticlesService.CreateArticle:input_type -> api.articles.v1.CreateArticleRequest
	9,  // 11: api.articles.v1.ArticlesService.UpdateArticle:input_type -> api.articles.v1.UpdateArticleRequest
	11, // 12: api.articles.v1.ArticlesService.DeleteArticle:input_type -> api.articles.v1.DeleteArticleRequest
	2,  // 13: api.articles.v1.ArticlesService.GetArticle:output_type -> api.articles.v1.GetArticleResponse
	4,  // 14: api.articles.v1.ArticlesService.GetArticleByDOI:output_type -> api.articles.v1.GetArticleByDOIResponse
	6,  // 15: api.articles.v1.ArticlesService.ListArticles:output_type -> api.articles.v1.ListArticlesResponse
	8,  // 16: api.articles.v1.ArticlesService.CreateArticle:output_type -> api.articles.v1.CreateArticleResponse
	10, // 17: api.articles.v1.ArticlesService.UpdateArticle:output_type -> api.articles.v1.UpdateArticleResponse
	12, // 18: api.articles.v1.ArticlesService.DeleteArticle:output_type -> api.articles.v1.DeleteArticleResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_articles_v1_article_proto_init() }
func file_articles_v1_article_proto_init() {
	if File_articles_v1_article_proto != nil {
		return
	}
	file_articles_v1_article_proto_msgTypes[0].OneofWrappers = []any{}
	file_articles_v1_article_proto_msgTypes[5].OneofWrappers = []any{}
	file_articles_v1_article_proto_msgTypes[7].OneofWrappers = []any{}
	file_articles_v1_article_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articles_v1_article_proto_rawDesc), len(file_articles_v1_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articles_v1_article_proto_goTypes,
		DependencyIndexes: file_articles_v1_article_proto_depIdxs,
		MessageInfos:      file_articles_v1_article_proto_msgTypes,
	}.Build()
	File_articles_v1_article_proto = out.File
	file_articles_v1_article_proto_goTypes = nil
	file_articles_v1_article_proto_depIdxs = nil
}
