server:
  host: localhost
  port: 50052
  useTLS: true
  certFile: "./testdata/certs/server.crt"
  keyFile: "./testdata/certs/server.key"
database:
  host: localhost
  port: 3306
  user: service
  password: service_password
  name: journalful
zitadel:
  domain: "auth.quantumdev.org"
  keypath: "./key.json"
  insecure: true