// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: profile/v1/author.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileId     int64                  `protobuf:"varint,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_profile_v1_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *Author) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Author) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type GetAuthorByProfileIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     int64                  `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorByProfileIDRequest) Reset() {
	*x = GetAuthorByProfileIDRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorByProfileIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorByProfileIDRequest) ProtoMessage() {}

func (x *GetAuthorByProfileIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorByProfileIDRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorByProfileIDRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorByProfileIDRequest) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

type GetAuthorByProfileIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorByProfileIDResponse) Reset() {
	*x = GetAuthorByProfileIDResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorByProfileIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorByProfileIDResponse) ProtoMessage() {}

func (x *GetAuthorByProfileIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorByProfileIDResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorByProfileIDResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthorByProfileIDResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{5}
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProfileId     *int64                 `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAuthorRequest) GetProfileId() int64 {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return 0
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the newly created author
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAuthorResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileId     *int64                 `protobuf:"varint,3,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthorRequest) Reset() {
	*x = UpdateAuthorRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorRequest) ProtoMessage() {}

func (x *UpdateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAuthorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAuthorRequest) GetProfileId() int64 {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return 0
}

type UpdateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthorResponse) Reset() {
	*x = UpdateAuthorResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthorResponse) ProtoMessage() {}

func (x *UpdateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthorResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{10}
}

type DeleteAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorRequest) Reset() {
	*x = DeleteAuthorRequest{}
	mi := &file_profile_v1_author_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorRequest) ProtoMessage() {}

func (x *DeleteAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAuthorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthorResponse) Reset() {
	*x = DeleteAuthorResponse{}
	mi := &file_profile_v1_author_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthorResponse) ProtoMessage() {}

func (x *DeleteAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_author_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthorResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthorResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_author_proto_rawDescGZIP(), []int{12}
}

var File_profile_v1_author_proto protoreflect.FileDescriptor

const file_profile_v1_author_proto_rawDesc = "" +
	"\n" +
	"\x17profile/v1/author.proto\x12\x0eapi.profile.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\x03R\tprofileId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x11GetAuthorResponse\x12.\n" +
	"\x06author\x18\x01 \x01(\v2\x16.api.profile.v1.AuthorR\x06author\"<\n" +
	"\x1bGetAuthorByProfileIDRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\x03R\tprofileId\"N\n" +
	"\x1cGetAuthorByProfileIDResponse\x12.\n" +
	"\x06author\x18\x01 \x01(\v2\x16.api.profile.v1.AuthorR\x06author\"\x14\n" +
	"\x12ListAuthorsRequest\"G\n" +
	"\x13ListAuthorsResponse\x120\n" +
	"\aauthors\x18\x01 \x03(\v2\x16.api.profile.v1.AuthorR\aauthors\"\\\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\x03H\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"&\n" +
	"\x14CreateAuthorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\x13UpdateAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\x03H\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"\x16\n" +
	"\x14UpdateAuthorResponse\"%\n" +
	"\x13DeleteAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x16\n" +
	"\x14DeleteAuthorResponse2\xbd\x04\n" +
	"\rAuthorService\x12P\n" +
	"\tGetAuthor\x12 .api.profile.v1.GetAuthorRequest\x1a!.api.profile.v1.GetAuthorResponse\x12q\n" +
	"\x14GetAuthorByProfileID\x12+.api.profile.v1.GetAuthorByProfileIDRequest\x1a,.api.profile.v1.GetAuthorByProfileIDResponse\x12V\n" +
	"\vListAuthors\x12\".api.profile.v1.ListAuthorsRequest\x1a#.api.profile.v1.ListAuthorsResponse\x12Y\n" +
	"\fCreateAuthor\x12#.api.profile.v1.CreateAuthorRequest\x1a$.api.profile.v1.CreateAuthorResponse\x12Y\n" +
	"\fUpdateAuthor\x12#.api.profile.v1.UpdateAuthorRequest\x1a$.api.profile.v1.UpdateAuthorResponse\x12Y\n" +
	"\fDeleteAuthor\x12#.api.profile.v1.DeleteAuthorRequest\x1a$.api.profile.v1.DeleteAuthorResponseB9Z7github.com/chiquitav2/journalful/pkg/profile/v1;profileb\x06proto3"

var (
	file_profile_v1_author_proto_rawDescOnce sync.Once
	file_profile_v1_author_proto_rawDescData []byte
)

func file_profile_v1_author_proto_rawDescGZIP() []byte {
	file_profile_v1_author_proto_rawDescOnce.Do(func() {
		file_profile_v1_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_author_proto_rawDesc), len(file_profile_v1_author_proto_rawDesc)))
	})
	return file_profile_v1_author_proto_rawDescData
}

var file_profile_v1_author_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_profile_v1_author_proto_goTypes = []any{
	(*Author)(nil),                       // 0: api.profile.v1.Author
	(*GetAuthorRequest)(nil),             // 1: api.profile.v1.GetAuthorRequest
	(*GetAuthorResponse)(nil),            // 2: api.profile.v1.GetAuthorResponse
	(*GetAuthorByProfileIDRequest)(nil),  // 3: api.profile.v1.GetAuthorByProfileIDRequest
	(*GetAuthorByProfileIDResponse)(nil), // 4: api.profile.v1.GetAuthorByProfileIDResponse
	(*ListAuthorsRequest)(nil),           // 5: api.profile.v1.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),          // 6: api.profile.v1.ListAuthorsResponse
	(*CreateAuthorRequest)(nil),          // 7: api.profile.v1.CreateAuthorRequest
	(*CreateAuthorResponse)(nil),         // 8: api.profile.v1.CreateAuthorResponse
	(*UpdateAuthorRequest)(nil),          // 9: api.profile.v1.UpdateAuthorRequest
	(*UpdateAuthorResponse)(nil),         // 10: api.profile.v1.UpdateAuthorResponse
	(*DeleteAuthorRequest)(nil),          // 11: api.profile.v1.DeleteAuthorRequest
	(*DeleteAuthorResponse)(nil),         // 12: api.profile.v1.DeleteAuthorResponse
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_profile_v1_author_proto_depIdxs = []int32{
	13, // 0: api.profile.v1.Author.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: api.profile.v1.Author.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.profile.v1.GetAuthorResponse.author:type_name -> api.profile.v1.Author
	0,  // 3: api.profile.v1.GetAuthorByProfileIDResponse.author:type_name -> api.profile.v1.Author
	0,  // 4: api.profile.v1.ListAuthorsResponse.authors:type_name -> api.profile.v1.Author
	1,  // 5: api.profile.v1.AuthorService.GetAuthor:input_type -> api.profile.v1.GetAuthorRequest
	3,  // 6: api.profile.v1.AuthorService.GetAuthorByProfileID:input_type -> api.profile.v1.GetAuthorByProfileIDRequest
	5,  // 7: api.profile.v1.AuthorService.ListAuthors:input_type -> api.profile.v1.ListAuthorsRequest
	7,  // 8: api.profile.v1.AuthorService.CreateAuthor:input_type -> api.profile.v1.CreateAuthorRequest
	9,  // 9: api.profile.v1.AuthorService.UpdateAuthor:input_type -> api.profile.v1.UpdateAuthorRequest
	11, // 10: api.profile.v1.AuthorService.DeleteAuthor:input_type -> api.profile.v1.DeleteAuthorRequest
	2,  // 11: api.profile.v1.AuthorService.GetAuthor:output_type -> api.profile.v1.GetAuthorResponse
	4,  // 12: api.profile.v1.AuthorService.GetAuthorByProfileID:output_type -> api.profile.v1.GetAuthorByProfileIDResponse
	6,  // 13: api.profile.v1.AuthorService.ListAuthors:output_type -> api.profile.v1.ListAuthorsResponse
	8,  // 14: api.profile.v1.AuthorService.CreateAuthor:output_type -> api.profile.v1.CreateAuthorResponse
	10, // 15: api.profile.v1.AuthorService.UpdateAuthor:output_type -> api.profile.v1.UpdateAuthorResponse
	12, // 16: api.profile.v1.AuthorService.DeleteAuthor:output_type -> api.profile.v1.DeleteAuthorResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_profile_v1_author_proto_init() }
func file_profile_v1_author_proto_init() {
	if File_profile_v1_author_proto != nil {
		return
	}
	file_profile_v1_author_proto_msgTypes[7].OneofWrappers = []any{}
	file_profile_v1_author_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_author_proto_rawDesc), len(file_profile_v1_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_author_proto_goTypes,
		DependencyIndexes: file_profile_v1_author_proto_depIdxs,
		MessageInfos:      file_profile_v1_author_proto_msgTypes,
	}.Build()
	File_profile_v1_author_proto = out.File
	file_profile_v1_author_proto_goTypes = nil
	file_profile_v1_author_proto_depIdxs = nil
}
