// Generated by the Gemini CLI. Do not edit.

import { Timestamp } from "@packages/grpc-client/google/protobuf/timestamp";

export interface Article {
  id: number;
  doi: string;
  title: string;
  /** List of authors */
  authors: Author[];
  abstract?: string | undefined;
  publicationYear?: number | undefined;
  journalName?: string | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface Author {
  id: number;
  name: string;
  profileId: number;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export enum ReadingStatus {
  READING_STATUS_UNSPECIFIED = 0,
  READING_STATUS_TO_READ = 1,
  READING_STATUS_READING = 2,
  READING_STATUS_READ = 3,
  READING_STATUS_ABANDONED = 4,
  UNRECOGNIZED = -1,
}

export interface Library {
  id: number;
  userId: number;
  name?: string | undefined;
  articles: LibraryArticle[];
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface LibraryArticle {
  id: number;
  articleId: number;
  readingStatus: ReadingStatus;
  addedAt: Date | undefined;
  notes?: string | undefined;
  articleTitle: string;
  doi: string;
  publicationYear: number;
}

export interface Profile {
  id: number;
  name: string;
  bio: string;
  institution: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}
