// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Article struct {
	ID              int64
	Doi             string
	Title           string
	Abstract        sql.NullString
	Url             sql.NullString
	PublicationYear sql.NullInt32
	JournalName     sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ArticleAuthor struct {
	ArticleID   int64
	AuthorID    int64
	AuthorOrder sql.NullInt32
	CreatedAt   sql.NullTime
}

type ArticleTag struct {
	ArticleID int64
	TagID     int64
	CreatedAt sql.NullTime
}

type Author struct {
	ID        int64
	Name      string
	ProfileID sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Library struct {
	ID          int64
	OwnerID     int64
	Name        sql.NullString
	Description sql.NullString
	Ispublic    sql.NullBool
	Isdefault   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type LibraryArticle struct {
	ID        int64
	LibraryID int64
	ArticleID int64
	// 0:Unspecified, 1:ToRead, 2:Reading, 3:Read, 4:Abandoned
	ReadingStatus   sql.NullInt16
	ReadingProgress sql.NullInt32
	Dateadded       sql.NullTime
	Datecompleted   sql.NullTime
	Notes           sql.NullString
	Isfavorite      sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Profile struct {
	ID          int64
	UserID      string
	Name        string
	Bio         sql.NullString
	Institution sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
