// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Article struct {
	ID              int64
	Doi             string
	Title           string
	Abstract        sql.NullString
	PublicationYear sql.NullInt32
	JournalName     sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ArticleAuthor struct {
	ArticleID   int64
	AuthorID    int64
	AuthorOrder sql.NullInt32
	CreatedAt   sql.NullTime
}

type Author struct {
	ID        int64
	Name      string
	ProfileID sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Library struct {
	ID        int64
	UserID    int64
	Name      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type LibraryArticle struct {
	ID        int64
	LibraryID int64
	ArticleID int64
	// 0:Unspecified, 1:ToRead, 2:Reading, 3:Read, 4:Abandoned
	ReadingStatus sql.NullInt16
	AddedAt       sql.NullTime
	Notes         sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Profile struct {
	ID          int64
	Name        string
	Bio         sql.NullString
	Institution sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
